# -*- coding: utf-8 -*-
"""GMTtoKST.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jGIQ5g7-TLcFOUYIuw6KTmDDWMss2biW
"""

import pandas as pd
from datetime import datetime, timedelta

# CSV 파일 읽기
df = pd.read_csv('/content/drive/MyDrive/20241129/xst600_database_SENSOR_DATA_TABLE_UTC.csv')

# saveDateTime 컬럼을 datetime 형식으로 변환
df['saveDateTime'] = pd.to_datetime(df['saveDateTime'])

# UTC에서 KST로 변환 (UTC + 9시간)
df['saveDateTime'] = df['saveDateTime'] + timedelta(hours=9)

# 변환된 시간을 원하는 형식으로 포맷팅 (예: YYYY-MM-DD HH:mm:ss)
df['saveDateTime'] = df['saveDateTime'].dt.strftime('%Y-%m-%d %H:%M:%S')

# 결과를 새로운 CSV 파일로 저장
df.to_csv('XST600_db_KST.csv', index=False)